services:
  npm_registry:
    container_name: menu-api-registry
    image: verdaccio/verdaccio
    restart: always
    domainname: "npm-registry.local"
    user: "501"
    ports:
      - "127.0.0.1:4873:4873"
    volumes:
      - "./volumes/npm-registry/conf:/verdaccio/conf"
      - "./volumes/npm-registry/storage:/verdaccio/storage"
      - "./volumes/npm-registry/plugins:/verdaccio/plugins"

  menu-api-postgres:
    container_name: menu-api-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '127.0.0.1:5500:5432'
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"

  menu-api:
    container_name: menu-api
    build: 
      context: ../../backend/menu-api/app
      dockerfile: Dockerfile
    image: menu-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@menu-api-postgres:5432/postgres
    depends_on:
      - menu-api-postgres
    ports:
      - '127.0.0.1:4000:3000'